_G.data:extend(
{
	{
		type = "recipe-category",
		name = "droids"
	},
	{
		type = "item-group",
		name = "droids",
		order = "f",
		icon = "__robotarmy__/graphics/icons/droid_group.png",
		icon_size = 64,
	},
	{
		type = "item-subgroup",
		name = "droid-combat-group",
		group = "combat",
		order = "c-2"
	},
	{
		type = "item",
		name = "droid-assembling-machine",
		icon = "__robotarmy__/graphics/icons/droid-assembling-machine.png",
		flags = { "goes-to-quickbar" },
		subgroup = "production-machine",
		order = "h[droid-assembling-machine]",
		place_result = "droid-assembling-machine",
		stack_size = 50
	},
	{
		type = "item",
		name = "droid-counter",
		icon = "__robotarmy__/graphics/icons/droid-counter.png",
		flags = { "goes-to-quickbar" },
		subgroup = "circuit-network",
		place_result = "droid-counter",
		order = "b[combinators]-e[droid-counter]",
		stack_size = 50,
	},
	{
		type = "item",
		name = "droid-settings",
		icon = "__robotarmy__/graphics/icons/droid-settings.png",
		flags = { "goes-to-quickbar" },
		subgroup = "circuit-network",
		place_result = "droid-settings",
		order = "b[combinators]-e[droid-settings]",
		stack_size = 50,
	},
	{
		type = "item",
		name = "guard-pole",
		icon = "__robotarmy__/graphics/icons/guard-pole.png",
		flags = { "goes-to-quickbar" },
		subgroup = "droid-combat-group",
		place_result = "guard-pole",
		order = "a[items]-d[guard-pole]",
		stack_size = 50,
	},
	{
		type = "selection-tool",
		name = "droid-selection-tool",
		icon = "__robotarmy__/graphics/icons/selection_tool.png",
		flags = { "goes-to-quickbar" },
		subgroup = "tool",
		order = "d[droid-control]-s[selection]",
		stack_size = 1,
		stackable = false,
		selection_color = { r = 0, g = 1, b = 0 },
		alt_selection_color = { r = 0, g = 1, b = 0 },
		selection_mode = { "matches-force" },
		alt_selection_mode = { "matches-force" },
		selection_cursor_box_type = "not-allowed",
		alt_selection_cursor_box_type = "not-allowed"
	},
	{
		type = "selection-tool",
		name = "droid-pickup-tool",
		icon = "__robotarmy__/graphics/icons/pickup_tool.png",
		flags = { "goes-to-quickbar" },
		subgroup = "tool",
		order = "d[droid-control]-p[pickup]",
		stack_size = 1,
		stackable = false,
		selection_color = { r = 1, g = 0, b = 0 },
		alt_selection_color = { r = 1, g = 0, b = 0 },
		selection_mode = { "blueprint" },
		alt_selection_mode = { "blueprint" },
		selection_cursor_box_type = "not-allowed",
		alt_selection_cursor_box_type = "not-allowed"
	},
})
